# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bees_solver}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aisha Fenton"]
  s.date = %q{2010-10-02}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{aisha.fenton@visfleet.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "examples/giochonda/canvas.rb",
     "examples/giochonda/gioconda-small.png",
     "examples/giochonda/gioconda.jpg",
     "examples/giochonda/gioconda.rb",
     "examples/giochonda/logo.jpeg",
     "examples/giochonda/logo2.jpeg",
     "examples/giochonda/moonman.gif",
     "examples/giochonda/simple.jpg",
     "examples/giochonda/test.rb",
     "examples/knapsack.rb",
     "examples/tsp/city.rb",
     "examples/tsp/data.rb",
     "examples/tsp/data/berlin52.rb",
     "examples/tsp/data/simple.rb",
     "examples/tsp/ext.rb",
     "examples/tsp/ext/array.rb",
     "examples/tsp/location.rb",
     "examples/tsp/results.csv",
     "examples/tsp/route.rb",
     "examples/tsp/tsp.rb",
     "examples/vrp/data/berlin52.rb",
     "examples/vrp/job.rb",
     "examples/vrp/location.rb",
     "examples/vrp/route.rb",
     "examples/vrp/schedule.rb",
     "examples/vrp/tsp.rb",
     "lib/bees_solver.java",
     "lib/bees_solver.rb",
     "lib/bees_solver/bee.rb",
     "lib/bees_solver/solver.rb"
  ]
  s.homepage = %q{http://github.com/aishafenton/bees_solver}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "examples/giochonda/canvas.rb",
     "examples/giochonda/gioconda.rb",
     "examples/giochonda/test.rb",
     "examples/knapsack.rb",
     "examples/tsp/city.rb",
     "examples/tsp/data/berlin52.rb",
     "examples/tsp/data/simple.rb",
     "examples/tsp/data.rb",
     "examples/tsp/ext/array.rb",
     "examples/tsp/ext.rb",
     "examples/tsp/location.rb",
     "examples/tsp/route.rb",
     "examples/tsp/tsp.rb",
     "examples/vrp/data/berlin52.rb",
     "examples/vrp/job.rb",
     "examples/vrp/location.rb",
     "examples/vrp/route.rb",
     "examples/vrp/schedule.rb",
     "examples/vrp/tsp.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

